### PR TITLE
chore: Added a changelog

### PR DESCRIPTION
**Pull request by shirblc**
---
name: Bug Fix / New Feature PR
about: PR to fix a bug / add a new feature.
title: ""
labels: ""
assignees: ""
---

**Description**
A clear and concise description of what the bug or the new feature is.

**Issue link**
If there is one, add a link to the open issue referencing this bug.

**Expected behavior**
For bugs: A clear and concise description of what you expected to happen.

**Your solution**
A clear and concise description of what you did to fix the bug or implement the new feature.

**Additional information**
Add any other information about the problem / feature request here.

### CODE REVIEW

**Review by danted22 — APPROVED** [review]

**Review by danted22 — APPROVED** [review]

**Review by danted22 — DISMISSED** [review]

**Comment by shirblc** [comment]
@danted22 This is _finally_ ready. When you approve it, do you mind briefly going through the headlines to make sure they're all fixed? I don't know why GH is weird with these sometimes but I had to fix quite a few of them

**Review by danted22 — APPROVED** [review]

**Comment by danted22** [comment]
CHecking headlines now

**Comment by danted22** [comment]
Checked and all look good to me!

**Comment by shirblc** [comment]
Ooh thank you! So we're good to go with this. Next step is to get something automated to run the updates, but that feels like a separate thing (presumably once the back-end's done too).

**Pull request merged**
