### PR TITLE
change: Replace Sass with Less

### PR DESCRIPTION
**Pull request by shirblc**
In https://github.com/sass/sass-site/issues/970 the Sass team essentially re-iterated that they promote hate speech, antisemitism and terrorism and are fine with it (as seen [here](https://github.com/sass/sass-site/commit/306fb8400b1a3258d8253a85e933b5d510aae25a)). We refuse to support this. Thus, we're moving away from Sass.

### CODE REVIEW

**Comment by shirblc** [comment]
This code's still not in a good shape, but I think at this point it's more urgent to get Sass out of this project, so it's worth merging (now that it finally looks roughly the way it was) and then continuing the fixes separately. @danted22, what do you think?

Okay I've just realised I forgot to fix the notifications tab, search and text size panel... but after those are fixed, the question remains whether to merge and then continue fixing.

**Review by danted22 — APPROVED** [review]
I think it's fine to merge and fix later. Once the user install base is higher, we might make different decisions but having the slightly broken sections gives incentive to come back and sort out.

**Comment by danted22** [comment]
Not sure if your code cov needs to pass before you can merge?

**Review by danted22 — APPROVED** [review]

**Comment by shirblc** [comment]
Fair point, let's go with that then. There's quite a bit more to do that's probably more urgent at the moment.

And no (not here at least), it's a little broken in the front-end... For some inexplicable reason it just keeps changing every time a change is made, even when it's just a dependencies change. Seems to indicate there's something wrong in either the coverage reports or the source maps, but every time I looked at it I got nowhere. This probably requires a proper deep dive but it's probably better to refactor some of that code first as there are quite a few uncovered lines that are uncovered because, well, they shouldn't be there in the first place.

Sorry about the last push btw, I thought I had that before 😅

Actually looks like it's still good so I'll just merge. Thank you for the quick review!

**Comment by danted22** [comment]
I think you're good to merge then 😉

**Comment by shirblc** [comment]
Oops, thought I did 🤣

**Pull request merged**
